// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oqnefuxrtlmahekirrcj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9xbmVmdXhydGxtYWhla2lycmNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMDk1MzcsImV4cCI6MjA2Mjc4NTUzN30.M_Ae7NZxZEnPFNVb4sSeT_NTwjkCw7Lp9kSrpwG7Iow";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);